name = "Assimp"
uuid = "079381af-6941-5802-8ad5-fb13e7f1c93a"
authors = ["Gnimuc <qiyupei@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
