[general]
library_name = "libassimp"
output_file_path = "./src/LibAssimp.jl"
module_name = "LibAssimp"
jll_pkg_name = "assimp_jll"
export_symbol_prefixes = ["ai", "AI"]
prologue_file_path = ""
header_blacklist = [".inl"]

printer_blacklist = [
    "AI_NO_EXCEPT",
]
